# Generated by Django 3.2.8 on 2021-10-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование модели')),
                ('slug', models.SlugField(unique=True)),
                ('amount', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('season', models.CharField(choices=[('Д', 'Демисезон'), ('Л', 'Лето'), ('З', 'Зима')], max_length=50, verbose_name='Сезон')),
                ('factory', models.CharField(max_length=50, verbose_name='Фабрика')),
                ('size', models.IntegerField(default=36, verbose_name='Размер обуви')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('Ж', 'Женский')], max_length=50, verbose_name='Пол')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dixi.category', verbose_name='Категория')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dixi.gallery', verbose_name='Фото')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dixi.material', verbose_name='Матераил')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена товара')),
                ('discount_bool', models.BooleanField(default=False, verbose_name='Наличие скидки')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('name_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_model_1', to='dixi.product', verbose_name='Модель')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dixi.product', verbose_name='Наименование модели'),
        ),
    ]
