# Generated by Django 3.2.8 on 2021-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='<font color="red">Цена пересчитывается автоматически,поле заполнять не нужно!</font>', max_digits=9, verbose_name='Цена товара с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
