# Generated by Django 3.2.8 on 2021-10-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0003_auto_20211030_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dixi.reviews', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dixi.product', verbose_name='Название продукта'),
        ),
    ]
