# Generated by Django 3.2.8 on 2021-11-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0004_auto_20211031_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена товара с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dixi.reviews', verbose_name='Родитель'),
        ),
    ]
