# Generated by Django 3.2.8 on 2021-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0005_auto_20211104_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Men'), ('Женский', 'Women')], max_length=50, verbose_name='Пол'),
        ),
    ]
