# Generated by Django 3.2.8 on 2021-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0006_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[(1, 'Мужской'), (2, 'Женский')], max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[(1, 'Демисезон'), (2, 'Лето'), (3, 'Зима')], max_length=50, verbose_name='Сезон'),
        ),
    ]
