# Generated by Django 3.2.8 on 2021-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dixi', '0007_auto_20211104_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Скидка в %'),
        ),
    ]
