# Generated by Django 3.2.8 on 2021-11-09 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dixi', '0009_reviews_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user'),
        ),
    ]
